 const president = [
    {
        id:1,
        name:"Ahmed Ben Bella",
        birthday:"25 décembre 1916",
        placeOfBirthday:"Maghnia",
        statut:"11 avril 2012",
        placeOfDaed:"Alger",
        title:"Premier Président de la République",
        presidence:"15 septembre 1963 — 19 juin 1965",
        img:"/president/benBella.jpg",
    },
    {
        id:2,
        name:"Houari Boumédiène",
        birthday:"23 août 1932",
        placeOfBirthday:"Guelma",
        statut:"11 avril 2012",
        placeOfDaed:"Alger",
        title:"Deuxième Président de la République",
        presidence:"19 juin 1965 — 27 décembre 1978",
        img:"/president/Houari_Boumediene's_Portrait.jpg",
    },
     {
        id:3,
        name:"Chadli Bendjedid",
        birthday:"14 avril 1929",
        placeOfBirthday:"Bouteldja",
        statut:"6 octobre 2012",
        placeOfDaed:"Alger",
        title:"Troisième Président de la République",
        presidence:"9 février 1979 — 11 janvier 1992",
        img:"/president/Chadli.jpg",
    },
    {
        id:4,
        name:"Mohamed Boudiaf",
        birthday:"223 juin 1919",
        placeOfBirthday:"M'Sila",
        statut:"29 juin 1992",
        placeOfDaed:"Annaba",
        title:"Président du Haut Comité d'État",
        presidence:"16 janvier 1992 — 29 juin 1992",
        img:"/president/Le_jeun_Mohamed_Boudiaf.jpg",
    },
    {
        id:5,
        name:"Ali Kafi",
        birthday:"17 octobre 1928",
        placeOfBirthday:"Jijel",
        statut:"16 avril 2013",
        placeOfDaed:"Alger",
        title:"Président du Haut Comité d'État",
        presidence:"2 juillet 1992 — 30 janvier 1994",
        img:"/president/Ali_Kafi_1992.jpg",
    },
    {
        id:6,
        name:"Liamine Zéroual",
        birthday:"3 juillet 1941",
        placeOfBirthday:"Batna",
        statut:"Vivant",
        placeOfDaed:"",
        title:"Quatrième Président de la République",
        presidence:"31 janvier 1994 — 27 avril 1999",
        img:"/president/Liamine_Zéroual.jpg",
    },
    {
        id:7,
        name:"Abdelaziz Bouteflika",
        birthday:"2 mars 1937",
        placeOfBirthday:"Oujda, Maroc",
        statut:"17 septembre 2021",
        placeOfDaed:"Alger",
        title:"Cinquième Président de la République",
        presidence:"27 avril 1999 — 2 avril 2019",
        img:"/president/bouteflka.jpg",
    },
    {
        id:8,
        name:"Abdelmadjid Tebboune",
        birthday:"17 novembre 1945",
        placeOfBirthday:"Mécheria",
        statut:"Président en exercice",
        placeOfDaed:"",
        title:"Sixième Président de la République",
        presidence:"Depuis le 19 décembre 2019",
        img:"/president/Abdelmadjid_Tebboune_(2023)_(cropped).jpg",
    },
]

module.exports = president